# Generated by Django 2.1 on 2018-08-20 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255, verbose_name='授業')),
                ('started_lesson', models.DateField(default=django.utils.timezone.now, verbose_name='受講日')),
                ('time', models.IntegerField(default=0, verbose_name='受講時間')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='名前')),
                ('gender', models.IntegerField(verbose_name='性別, choices=gender_choices')),
                ('age', models.IntegerField(default=0, verbose_name='年齢')),
            ],
        ),
    ]
