# Generated by Django 2.1 on 2018-08-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='started_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
    ]
