# Generated by Django 2.1 on 2018-08-24 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_auto_20180825_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0, verbose_name='受講時間')),
                ('attended', models.DateTimeField(default=django.utils.timezone.now, verbose_name='受講日')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_admin.Lesson', verbose_name='授業')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_admin.User', verbose_name='顧客')),
            ],
        ),
    ]
