# Generated by Django 2.1 on 2018-08-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_attend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_count', models.IntegerField(verbose_name='レッスン数')),
                ('total', models.IntegerField(verbose_name='合計')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_admin.User', verbose_name='顧客')),
            ],
        ),
    ]
