# Generated by Django 2.1 on 2018-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0005_auto_20180825_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='user',
            field=models.IntegerField(verbose_name='顧客'),
        ),
    ]
