# Generated by Django 2.1 on 2018-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0006_auto_20180825_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='user',
            field=models.CharField(max_length=255, verbose_name='顧客'),
        ),
    ]
