# Generated by Django 2.1 on 2018-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0007_auto_20180825_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='lesson',
            field=models.CharField(max_length=255, verbose_name='授業'),
        ),
    ]
