# Generated by Django 2.1 on 2018-08-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0008_auto_20180825_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_admin.Lesson', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_admin.User', verbose_name='顧客'),
        ),
    ]
