# Generated by Django 2.1 on 2018-08-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0009_auto_20180825_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(verbose_name='基本料金')),
                ('basic_charge', models.IntegerField(verbose_name='従量料金')),
                ('over_20h_basic_charge', models.IntegerField(verbose_name='20時間超過料金')),
                ('over_35h_basic_charge', models.IntegerField(verbose_name='35時間超過料金')),
                ('over_50h_basic_charge', models.IntegerField(verbose_name='50時間超過料金')),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_admin.Lesson', verbose_name='授業')),
            ],
        ),
    ]
